// components/TableData3.js

const TableData3 = () => {
  return [
    { cityId: 1, cityName: 'New York' },
    { cityId: 2, cityName: 'Los Angeles' },
    { cityId: 3, cityName: 'Chicago' },
    { cityId: 4, cityName: 'Houston' },
    { cityId: 5, cityName: 'Phoenix' },
    { cityId: 6, cityName: 'Philadelphia' },
    { cityId: 7, cityName: 'San Antonio' },
    { cityId: 8, cityName: 'San Diego' },
    { cityId: 9, cityName: 'Dallas' },
    { cityId: 10, cityName: 'San Jose' },
    { cityId: 11, cityName: 'Austin' },
    { cityId: 12, cityName: 'Jacksonville' },
    { cityId: 13, cityName: 'Fort Worth' },
    { cityId: 14, cityName: 'Columbus' },
    { cityId: 15, cityName: 'Charlotte' },
    { cityId: 16, cityName: 'Indianapolis' },
    { cityId: 17, cityName: 'Seattle' },
    { cityId: 18, cityName: 'Denver' },
    { cityId: 19, cityName: 'Washington' },
    { cityId: 20, cityName: 'Boston' },
    { cityId: 21, cityName: 'El Paso' },
    { cityId: 22, cityName: 'Nashville' },
    { cityId: 23, cityName: 'Detroit' },
    { cityId: 24, cityName: 'Oklahoma City' },
    { cityId: 25, cityName: 'Portland' },
    { cityId: 26, cityName: 'Las Vegas' },
    { cityId: 27, cityName: 'Memphis' },
    { cityId: 28, cityName: 'Louisville' },
    { cityId: 29, cityName: 'Baltimore' },
    { cityId: 30, cityName: 'Milwaukee' },
    { cityId: 31, cityName: 'Albuquerque' },
    { cityId: 32, cityName: 'Tucson' },
    { cityId: 33, cityName: 'Fresno' },
    { cityId: 34, cityName: 'Sacramento' },
    { cityId: 35, cityName: 'Mesa' },
    { cityId: 36, cityName: 'Atlanta' },
    { cityId: 37, cityName: 'Kansas City' },
    { cityId: 38, cityName: 'Colorado Springs' },
    { cityId: 39, cityName: 'Miami' },
    { cityId: 40, cityName: 'Raleigh' },
    { cityId: 41, cityName: 'Omaha' },
    { cityId: 42, cityName: 'Long Beach' },
    { cityId: 43, cityName: 'Virginia Beach' },
    { cityId: 44, cityName: 'Oakland' },
    { cityId: 45, cityName: 'Minneapolis' },
    { cityId: 46, cityName: 'Tampa' },
    { cityId: 47, cityName: 'Arlington' },
    { cityId: 48, cityName: 'Wichita' },
    { cityId: 49, cityName: 'Bakersfield' },
    { cityId: 50, cityName: 'New Orleans' }
  ];
};

export default TableData3;
